name: my_environment
channels:
  - defaults
dependencies:
  - aiohttp==3.9.5
  - aiosignal==1.3.1
  - anaconda-client @ file:///opt/concourse/worker/volumes/live/866d4dd0-ff5b-4d0b-718d-0267a3b10e06/volume/anaconda-client_1635342573767/work
  - anaconda-navigator==2.1.1
  - anaconda-project @ file:///tmp/build/80754af9/anaconda-project_1626085644852/work
  - anyio @ file:///opt/concourse/worker/volumes/live/96440bbe-d2f1-4a9e-5edf-600248ff38bd/volume/anyio_1617783321037/work/dist
  - appdirs==1.4.4
  - applaunchservices @ file:///Users/ktietz/demo/mc3/conda-bld/applaunchservices_1630511705208/work
  - appnope @ file:///opt/concourse/worker/volumes/live/6ca6f098-d773-4461-5c91-a24a17435bda/volume/appnope_1606859448531/work
  - appscript @ file:///opt/concourse/worker/volumes/live/00049ed6-6263-4a6e-72b9-9d990f6e2f07/volume/appscript_1611427000595/work
  - argh==0.26.2
  - argon2-cffi @ file:///opt/concourse/worker/volumes/live/38e8fb2b-1295-4bdf-4adf-b20acbe4d91b/volume/argon2-cffi_1607022498041/work
  - arrow @ file:///opt/concourse/worker/volumes/live/1c202787-83f7-4b70-6d98-b40769f597f4/volume/arrow_1617737667847/work
  - asgiref==3.5.0
  - asn1crypto @ file:///tmp/build/80754af9/asn1crypto_1596577642040/work
  - astroid @ file:///opt/concourse/worker/volumes/live/5aff3c6b-d8ac-4e74-4846-0f446794397d/volume/astroid_1628063157520/work
  - astropy @ file:///opt/concourse/worker/volumes/live/dac790a5-ee97-4520-5b55-f2cc50d275e6/volume/astropy_1629829220593/work
  - async-generator @ file:///home/ktietz/src/ci/async_generator_1611927993394/work
  - async-timeout==4.0.3
  - atomicwrites==1.4.0
  - attrs @ file:///tmp/build/80754af9/attrs_1620827162558/work
  - autopep8 @ file:///tmp/build/80754af9/autopep8_1620866417880/work
  - Babel @ file:///tmp/build/80754af9/babel_1620871417480/work
  - backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
  - backports.functools-lru-cache @ file:///tmp/build/80754af9/backports.functools_lru_cache_1618170165463/work
  - backports.shutil-get-terminal-size @ file:///tmp/build/80754af9/backports.shutil_get_terminal_size_1608222128777/work
  - backports.tempfile @ file:///home/linux1/recipes/ci/backports.tempfile_1610991236607/work
  - backports.weakref==1.0.post1
  - beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1631874778482/work
  - binaryornot @ file:///tmp/build/80754af9/binaryornot_1617751525010/work
  - bitarray @ file:///opt/concourse/worker/volumes/live/8f2b2fa2-f7cd-4343-4d8f-3cc38b632e33/volume/bitarray_1629132852828/work
  - bkcharts==0.2
  - black==19.10b0
  - bleach @ file:///tmp/build/80754af9/bleach_1628110601003/work
  - bokeh @ file:///opt/concourse/worker/volumes/live/278130e0
  - boto=2.49.0
  - bottleneck
  - brotlipy=0.7.0
  - cached-property
  - certifi=2024.6.2
  - cffi
  - chardet
  - charset-normalizer
  - click=8.0.3
  - cloudpickle
  - clyent=1.2.2
  - colorama
  - conda=4.14.0
  - conda-build=3.21.5
  - conda-content-trust
  - conda-pack
  - conda-package-handling
  - conda-repo-cli
  - conda-token
  - conda-verify=3.4.2
  - contextlib2
  - cookiecutter
  - cryptography
  - cycler=0.10.0
  - Cython
  - cytoolz=0.11.0
  - daal4py==2021.3.0
  - dask==2021.10.0
  - debugpy
  - decorator
  - defusedxml
  - diff-match-patch
  - discord.py==2.3.2
  - distlib==0.3.4
  - distributed
  - Django==4.0.3
  - django-countries==7.3.2
  - docutils
  - entrypoints==0.3
  - et-xmlfile==1.1.0
  - fastcache
  - filelock
  - flake8
  - Flask
  - fonttools==4.25.0
  - frozenlist==1.4.1
  - fsspec
  - future
  - gevent
  - glob2
  - gmpy2==2.0.8
  - greenlet
  - h5py
  - HeapDict
  - html5lib
  - huggingface-hub==0.13.4
  - idna
  - imagecodecs
  - imageio
  - imagesize
  - importlib-metadata
  - inflection==0.5.1
  - iniconfig
  - intervaltree
  - ipykernel
  - ipython
  - ipython-genutils
  - ipywidgets
  - isort
  - itsdangerous
  - jdcal
  - jedi
  - Jinja2
  - jinja2-time
  - joblib
  - json5
  - jsonschema
  - jupyter
  - jupyter-client
  - jupyter-console
  - jupyter-core
  - jupyter-server
  - jupyterlab
  - jupyterlab-pygments
  - jupyterlab-server
  - jupyterlab-widgets
  - keyring
  - kiwisolver
  - lazy-object-proxy
  - libarchive-c
  - llvmlite==0.37.0
  - localflavor==1.9
  - locket==0.2.1
  - lxml
  - MarkupSafe
  - matplotlib
  - matplotlib-inline
  - mccabe==0.6.1
  - mistune
  - mkl-fft==1.3.1
  - mkl-random
  - mkl-service==2.4.0
  - mock
  - more-itertools
  - mpmath==1.2.1
  - msgpack
  - multidict==6.0.5
  - multipledispatch
  - munkres==1.1.4
  - mypy-extensions==0.4.3
  - navigator-updater==0.2.1
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx
  - nltk==3.6.5
  - nose
  - notebook
  - numba
  - numexpr
  - numpy
  - numpydoc
  - olefile
  - openpyxl
  - packaging
  - pandas==1.3.4
  - pandocfilters
  - parso
  - partd
  - path
  - pathlib2
  - pathspec==0.7.0
  - patsy==0.5.2
  - pep8==1.7.1
  - pexpect
  - pickleshare
  - Pillow==8
  - pkginfo==1.7.1
  - platformdirs==2.5.2
  - pluggy
  - ply==3.11
  - poyo
  - prometheus-client
  - prompt-toolkit
  - psutil
  - psycopg2-binary==2.9.9
  - ptyprocess
  - py
  - pycodestyle
  - pycosat==0.6.3
  - pycparser
  - pycurl==7.44.1
  - pydocstyle
  - pyerfa
  - pyflakes
  - Pygments
  - PyJWT
  - pylint
  - pyls-spyder==0.4.0
  - pyodbc===4.0.0-unsupported
  - pyOpenSSL
  - pyparsing
  - pyrsistent
  - PySocks
  - pytest==6.2.4
  - python-dateutil
  - python-dotenv==1.0.1
  - python-lsp-black
  - python-lsp-jsonrpc==1.0.0
  - python-lsp-server==1.2.4
  - python-slugify
  - pytz==2021.3
  - PyWavelets
  - PyYAML==6.0
  - pyzmq
  - QDarkStyle
  - qstylizer
  - QtAwesome
  - qtconsole
  - QtPy
  - regex
  - reportlab==3.6.9
  - requests
  - rope
  - Rtree
  - ruamel-yaml-conda
  - scikit-image==0.18.3
  - scikit-learn
  - scikit-learn-intelex==2021.20210714.100439
  - scipy
  - seaborn
  - Send2Trash
  - simplegeneric==0.8.1
  - singledispatch
  - sip==4.19.13
  - six
  - sniffio
  - snowballstemmer
  - sortedcollections
  - sortedcontainers
  - soupsieve
  - Sphinx==4.2.0
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-websupport
  - spyder
  - spyder-kernels
  - SQLAlchemy
  - sqlparse==0.4.2
  - statsmodels
  - stripe==2.73.0
  - sympy
  - tables
  - TBB==0.2
  - tblib
  - terminado==0.9.4
  - testpath
  - text-unidecode
  - textdistance
  - threadpoolctl
  - three-merge
  - tifffile
  - tinycss
  - toml
  - toolz
  - torch==1.10.2
  - torchaudio==0.10.2
  - torchvision==0.11.3
  - tornado
  - tqdm
  - traitlets
  - typed-ast
  - typing-extensions
  - ujson
  - unicodecsv==0.14.1
  - Unidecode
  - urllib3==1.26.7
  - virtualenv==20.15.1
  - watchdog
  - wcwidth
  - webencodings
  - Werkzeug
  - wget==3.2
  - whichcraft
  - widgetsnbextension
  - wrapt
  - wurlitzer
  - xlrd
  - XlsxWriter
  - xlwings==0.24.9
  - xlwt==1.3.0
  - xmltodict
  - yapf
  - yarl==1.9.4
  - zict==2.0.0
  - zipp
  - zope.event==4.5.0
  - zope.interface